base_url = "https://omidnw.github.io/Web-Core"
compile_sass = true
title = "Web Core"
description = "Create & Use & Build With C Programming Language!"
highlight_code = true
build_search_index = true

[extra]
book_number_chapters = true
